### ISSUE TITLE
Add CORS header

### ISSUE THREAD

**Issue by naveen521kk** [xinitrc-ls/randomfox.ca#10]
I just want some fox in my website which has is fully JavaScript based. I get some errors as this site doesn't support [cors](https://en.m.wikipedia.org/wiki/Cross-origin_resource_sharing). You could visit below links to set it up and it is quite important for JS based apps which run in browser. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://stackoverflow.com/questions/8719276/cross-origin-request-headerscors-with-php-headers

Thanks in advance 👍

**Comment by xinitrc-dev** [comment]
Thanks for letting me know!
Would a simple "Access-Control-Allow-Origin: *" suffice?

**Comment by naveen521kk** [comment]
I think it would do!

**Comment by xinitrc-dev** [comment]
Great! Fixed in https://github.com/xinitrc-dev/randomfox.ca/commit/41994873c0c43be85506d383512a980d49642ef6

**Comment by naveen521kk** [comment]
@xinitrc-dev I made the site https://fox.syrusdark.website/
If that looks good I will make a PR to make it as home page!
Its fully JS and HTML

**Comment by xinitrc-dev** [comment]
The website will undergo a pretty heavy revamp. This design looks better for the API hub, rather than for the mainpage. Keep the code, as it might prove useful for the redesign :) I can't really be any more specific right now as im still working on the structure and things, Ill let you know when Im ready for the actual home page redesign tho!
